# Generated by Django 4.2 on 2024-05-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles_app', '0005_rename_seo_description_articlemodel_meta_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='tag',
            new_name='tags',
        ),
    ]
