# Generated by Django 4.2 on 2024-06-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles_app", "0006_rename_tag_articlemodel_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/articles/"
            ),
        ),
    ]
